personalLib/library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
    path('', views.HomeView.as_view(), name='library_home'),
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('catalog/system/', views.CatalogSystemView.as_view(), name='catalog_system'),
    path('catalog/codes/', views.DeterminantsView.as_view(), name='catalog_codes'),
]

personalLib/personalLib/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

personalLib/library/models.py
from django.db import models
from django.contrib import admin


class Author(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    nacionalidad = models.CharField(max_length=100)

    def __str__(self):
        # return '{}, {}'.format(self.apellido, self.nombre)
        return '{} {}'.format(self.nombre, self.apellido)

    class Meta:
        db_table = 'tblautores'


class Publisher(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'tbleditoriales'


class Book(models.Model):
    libro_id = models.CharField(max_length=20)
    titulo = models.TextField()
    autor = models.ForeignKey(Author, on_delete=models.CASCADE)
    editorial = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pags = models.IntegerField(default=0)
    isbn = models.CharField(max_length=21)
    ejemplares = models.IntegerField(default=1)
    leido = models.BooleanField(default=False)
    observaciones = models.TextField()

    def get_author_id(self):
        return int(self.autor.id)

    def book_read_icon(self):
        """Function to help to recognise the `read` field as a Python Boolean"""
        if self.leido:
            return "fa-solid fa-circle-check true"
        else:
            return "fa-solid fa-circle-xmark false"

    def __str__(self):
        return '{}, \"{}\", by {}'.format(self.libro_id, self.titulo, self.autor.nombre)

    class Meta:
        db_table = 'tbllibros'


class DeweySystem(models.Model):
    id = models.CharField(max_length=4, primary_key=True)
    nombre = models.TextField()

    class Meta:
        db_table = 'tblclasificaciondewey'


class LiteratureInSpanish(models.Model):
    id = models.CharField(max_length=4, primary_key=True)
    pais = models.CharField(max_length=50)

    class Meta:
        db_table = 'tblliteraturahispanoamericana_860'


class CatalogCodes(models.Model):
    num = models.CharField(max_length=10)
    determinante = models.CharField(max_length=100)

    class Meta:
        db_table = 'tbldetforma'


class LanguageCodes(models.Model):
    num = models.CharField(max_length=10)
    determinante = models.CharField(max_length=100)

    class Meta:
        db_table = 'tbldetlengua'


class HistoryCodes(models.Model):
    num = models.CharField(max_length=10)
    determinante = models.CharField(max_length=100)

    class Meta:
        db_table = 'tbldethistoria'


class LiteratureCodes(models.Model):
    num = models.CharField(max_length=10)
    determinante = models.CharField(max_length=100)

    class Meta:
        db_table = 'tbldetliteratura'


class AuthorNameCodes(models.Model):
    numero = models.CharField(max_length=1)
    letras = models.CharField(max_length=18)

    class Meta:
        db_table = 'tbldetnombreautor'

personalLib/library/views.py
import unidecode

from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Author, Publisher, Book
from .models import DeweySystem, CatalogCodes
from .models import AuthorNameCodes, HistoryCodes, LanguageCodes, LiteratureCodes, LiteratureInSpanish


class HomeView(LoginRequiredMixin, generic.base.TemplateView):
    """View class for the home page"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_books'] = Book.objects.all().count()
        context['total_authors'] = Author.objects.all().count()
        return context
    

class BookListView(LoginRequiredMixin, generic.ListView):
    """View class for the list of all books"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/book_list.html'
    context_object_name = 'book_list'

    def get_queryset(self):
        """Return all books, ordered by Catalog Id"""
        return Book.objects.order_by('libro_id')


class AuthorListView(LoginRequiredMixin, generic.ListView):
    """View class for the list of all authors"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/author_list.html'
    context_object_name = 'author_list'

    def get_queryset(self):
        """Return all authors, ordered ba Family Name"""
        return Author.objects.order_by('apellido')
    

class BookDetailView(LoginRequiredMixin, generic.DetailView):
    """View class for the detailed view of a particular book"""
    
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    
    template_name = 'library/book_detail.html'
    model = Book


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    """View class for the detailed view of a particular author"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/author_detail.html'
    model = Author

    def get_context_data(self, **kwargs):
        """Add to the context all books associated with this Author"""
        context = super().get_context_data(**kwargs)
        context['books_by'] = Book.objects.filter(autor=self.get_object())
        context['name_code'] = self.get_name_code()
        return context

    def get_name_code(self):
        text = unidecode.unidecode(getattr(self.get_object(), 'apellido'))
        if len(text) < 3:
            return text[0]
        num_1 = getattr(
            AuthorNameCodes.objects.filter(letras__contains=text[1].lower()).first(),
            'numero'
        )
        num_2 = getattr(
            AuthorNameCodes.objects.filter(letras__contains=text[2].lower()).first(),
            'numero'
        )
        return '{}{}{}'.format(text[0], num_1, num_2)


class CatalogSystemView(LoginRequiredMixin, generic.ListView):
    """View class for the whole Dewey-Catalog system, used to catalog the whole library.\n
    Use it only as a reference"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/dewey_system.html'
    context_object_name = 'determinants'

    def get_queryset(self):
        """Return all the Ids and Subjects of the catalog (Dewey System)"""
        return DeweySystem.objects.order_by('id')


class DeterminantsView(LoginRequiredMixin, generic.ListView):
    """View class for the different determinants (Form, Language, History, Author Name),
    used to catalog the whole library.\n
    Use it only as a reference"""

    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    template_name = 'library/catalog_codes.html'
    context_object_name = 'determinants'

    def get_queryset(self):
        """Return all the Ids and Subjects of the catalog (Dewey System)"""
        return CatalogCodes.objects.order_by('id')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['det_language'] = LanguageCodes.objects.all().order_by('num')
        context['det_history'] = HistoryCodes.objects.all().order_by('num')
        context['det_literature'] = LiteratureCodes.objects.all().order_by('num')
        context['det_spanish_lit'] = LiteratureInSpanish.objects.all().order_by('id')
        context['det_author_name'] = AuthorNameCodes.objects.all().order_by('numero')
        return context

personalLib/library/templates/base/generic.html
<!-- Based on the model by developer.mozilla.org -->
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}<title>Carlos Library. A Django Project</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}
        <link rel="stylesheet" href="{% static 'library/styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <!-- SIDEBAR -->
        {% include "base/sidebar.html" %}
        
        <!-- CONTENT -->
        {% block content %}{% endblock %}
    </body>
</html>

personalLib/library/templates/base/sidebar.html
<div class="sidebar">
    <!-- Title -->
    <div class="bar-title">
        Carlos' Personal Library
    </div>
    <!-- Links -->
    <div class="bar-block">
        {% if user.is_authenticated %}
            <a href="{% url 'library:library_home' %}"
               class="bar-item bar-button">
                <i class="fa-solid fa-house-chimney"></i>&nbsp;&nbsp;Home
            </a>
            <a href="{% url 'library:book_list' %}"
               class="bar-item bar-button">
                <i class="fa-solid fa-book no-hover"></i>&nbsp;&nbsp;All books
            </a>
            <a href="{% url 'library:author_list' %}"
               class="bar-item bar-button">
                <i class="fa-solid fa-user-pen"></i>&nbsp;&nbsp;All authors
            </a>
            <a href=""
               class="bar-item bar-button">
                <i class="fa-solid fa-lock"></i>&nbsp;&nbsp;Admin
            </a>
            <br>
            <br>
            <br>
            <button class="accordion bar-item bar-button" onclick="myAccFunc()">
                Catalogation <i class="fa fa-caret-down"></i>
             </button>
            <div class="accordion-panel">
                <a href="{% url 'library:catalog_system' %}"
                   class="bar-item bar-button">
                   <i class="fa-solid fa-hashtag"></i>&nbsp;&nbsp;Codification
                </a>
                <a href="{% url 'library:catalog_codes' %}"
                   class="bar-item bar-button">
                   <i class="fa-solid fa-hashtag"></i>&nbsp;&nbsp;Determinants
                </a>
            </div>
            <br>
            <br>
            <br>
            <div class="bar-item">
                Hi {{ user.get_username }}!
            </div>
            <a href="{% url 'logout' %}?next={{request.path}}"
            class="bar-item bar-button">
                <i class="fa-solid fa-arrow-right-from-bracket"></i>&nbsp;&nbsp;Logout
            </a>
        {% else %}
        <a href="{% url 'login' %}?next={{request.path}}"
        class="bar-item bar-button">
            <i class="fa-solid fa-arrow-right-to-bracket"></i>&nbsp;&nbsp;Login
        </a>
        {% endif %}
    </div>
</div>

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i=0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
            }
        });
    }
</script>

personalLib/library/templates/library/author_detail.html
{% extends 'base/generic.html' %}

{% block content %}
    <!-- Author detail -->
    <div class="container-card">
        <div class="panel card card-dark">
            <h1>Author Details. DB_ID: {{ author.id }}</h1>
            <h2>Details</h2>
            <div class="form-item">
                <p class="form-label">Name</p>
                <input type="text" name="Name" value="{{ author.nombre }}"
                    id="Name" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">Family Name</p>
                <input type="text" name="FamilyName" value="{{ author.apellido }}"
                    id="FamilyName" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">Nationality</p>
                <input type="text" name="Country" value="{{ author.nacionalidad }}"
                    id="Country" class="form-style"/>
            </div>
            <div class="form-item">
                Coded Name: {{ name_code }}
            </div>
        </div>
    </div>
    <!-- Author Image -->
    <div class="container-card">
        <div class="polaroid card-dark">
            <a href="https://www.wikipedia.com/">
                <img src="https://t3.ftcdn.net/jpg/02/18/08/74/360_F_218087403_fSOfyVN3azDznIeQ1rFCmd6bXAz9CbXi.jpg"
                        alt="{{ author }}"
                        style="width: 100%; border-radius: 5px;">
                <div class="container-card">
                    <p class="text-center">{{ author }}</p>
                </div>                        
            </a>
            </div>
    </div>
    <!-- Books in Catalog by the author -->
    {% if books_by %}
        <div class="container-card">
            <div class="panel card-low">
                <div class="card-dark-small">
                    <p>Books in catalog written by {{ author }}</p>
                </div>                
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Book Id</th>
                                <th>Title</th>
                                <th>Publisher</th>
                                <th>ISBN</th>
                            </tr>
                        </thead>
                            <tbody>
                                {% for book in books_by %}
                                    <tr>
                                        <th scope="row">
                                            <a href="{% url 'library:book_detail' book.id %}">
                                                {{ book.libro_id }}
                                            </a>
                                        </th>
                                        <td>{{ book.titulo }}</td>
                                        <td>{{ book.editorial }}</td>
                                        <td>{{ book.isbn }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

personalLib/library/templates/library/author_list.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Author List</h2>
            </div>
        </div>
        {% if author_list %}
            <div class="row">
                <div class="col-md-4">
                    <div class="table-wrap">
                        <table class="table table-bordered table-dark table-hover table-narrow">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Nationality</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for author in author_list %}
                                    <tr>
                                        <th scope="row">
                                            <a href="{% url 'library:author_detail' author.id %}">
                                                {{ author.id }}
                                            </a>
                                        </th>
                                        <td>{{ author.nombre }}</td>
                                        <td>
                                            {{ author.apellido }}
                                        </td>
                                        <td>{{ author.nacionalidad }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% else %}
            <p>No author list available/found.</p>
        {% endif %}
    </div>
{% endblock %}

personalLib/library/templates/library/book_detail.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container-card">
        <div class="panel card card-dark">
            <h1>Book Details. DB_ID: {{ book.id }}</h1>
            <!-- DETAILS -->
            <h2>Details</h2>
            <br>
            <div class="form-item">
                <p class="form-label">Title</p>
                <input type="text" name="Title" value="{{ book.titulo }}"
                    id="Title" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">Author</p>
                <input type="text" name="Author" value="{{ book.autor }}"
                    id="Author" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">Num. Pags.</p>
                <input type="value" name="NumPags" value="{{ book.pags }}"
                    id="Pags" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">Publisher</p>
                <input type="text" name="Editor" value="{{ book.editorial }}"
                    id="Editor" class="form-style"/>
            </div>
            <!-- <br> -->
            <!-- IDs -->
            <h2>ID Numbers</h2>
            <div class="form-item">
                <p class="form-label">Catalog Id</p>
                <input type="text" name="BookId" value="{{ book.libro_id }}"
                    id="BookId" class="form-style"/>
            </div>
            <div class="form-item">
                <p class="form-label">ISBN</p>
                <input type="text" name="ISBN" value="{{ book.isbn }}"
                    id="ISBN" class="form-style"/>
            </div>
            <!-- <br> -->
            <!-- COMMENTS -->
            <h2>Notes / Comments</h2>
            <div class="form-item">
                <label class="form-check">
                    Read?
                    <input type="checkbox" {% if book.leido %} checked {% endif %}>
                    <span class="checkmark"></span>
                </label>

            </div>
            <br>
            <div class="form-item">
                <p class="form-label">Comments</p>
                <input type="text" name="Comments" value="{{ book.observaciones }}"
                    id="Comments" class="form-style"/>
            </div>
            <!-- BACK BUTTON -->
            <!-- <a href="{% url 'library:book_list' %}">
                <input type="submit" class="back pull-right" value="Back to List">
            </a>
            <div class="clear-fix"></div> -->
        </div>
    </div>
{% endblock %}

personalLib/library/templates/library/book_list.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <!-- <div class="col-md-12 text-center mb-12"> -->
                <h2 class="heading-section">Book List</h2>
            <!-- </div> -->
        </div>
        {% if book_list %}
            <div class="row">
                <!-- <div class="col-md-12"> -->
                    <div class="table-wrap">
                        <table class="table table-bordered table-dark table-hover">
                            <thead>
                                <tr>
                                    <th>Book Id</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Num. Pags</th>
                                    <th>Publisher</th>
                                    <th>ISBN</th>
                                    <th>Read?</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for book in book_list %}
                                    <tr>
                                        <th scope="row">
                                            <a href="{% url 'library:book_detail' book.id %}">
                                                {{ book.libro_id }}
                                            </a>
                                        </th>
                                        <td>{{ book.titulo }}</td>
                                        <td>
                                            <a href="{% url 'library:author_detail' book.autor.id %}">
                                                {{ book.autor }}
                                            </a>
                                        </td>
                                        <td>{{ book.pags }}</td>
                                        <td>{{ book.editorial }}</td>
                                        <td>{{ book.isbn }}</td>
                                        <!-- <td>{{ book.leido }}</td> -->
                                        <td>
                                            <i class="{{ book.book_read_icon }}"></i>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                <!-- </div> -->
            </div>
        {% else %}
            <p>No book list available/found.</p>
        {% endif %}
    </div>
{% endblock %}

personalLib/library/templates/library/catalog_codes.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <h2 class="heading-section">Used Dewey Catalogation System</h2>
        </div>
    </div>

    <div class="row-padding margin-top">

        <div class="card-fourth" style="margin-left: 200px;">
            {% if determinants %}
                <h3>General Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in determinants %}
                                <tr>
                                    <td>{{ d.num }}</td>
                                    <td>{{ d.determinante }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No catalog items are available/found for Catalog Codes</p>
            {% endif %}
        </div>

        <div class="card-fourth">
            {% if det_language %}
                <h3>Language Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in det_language %}
                                <tr>
                                    <td>{{ d.num }}</td>
                                    <td>{{ d.determinante }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> 
            {% else %}
                <p>No catalog items are available/found for Language Codes</p>
            {% endif %}
        </div>

        <div class="card-fourth">
            {% if det_history %}
                <h3>History Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in det_history %}
                                <tr>
                                    <td>{{ d.num }}</td>
                                    <td>{{ d.determinante }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No catalog items are available/found for History Codes</p>
            {% endif %}
        </div>

    </div>

    <div class="row-padding margin-top">

        <div class="card-fourth" style="margin-left: 200px;">
            {% if det_author_name %}
                <h3>Author Name Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Letters</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in det_author_name %}
                                <tr>
                                    <td>{{ d.numero }}</td>
                                    <td>{{ d.letras }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No catalog items are available/found for Author Name Codes</p>
            {% endif %}
        </div>


        <div class="card-fourth">
            {% if det_literature %}
                <h3>Literature Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Number</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in det_literature %}
                                <tr>
                                    <td>{{ d.num }}</td>
                                    <td>{{ d.determinante }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No catalog items are available/found for Literature Codes</p>
            {% endif %}
        </div>

        <div class="card-fourth">
            {% if det_spanish_lit %}
                <h3>Literature in Spanish Codes</h3>
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover">
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Country</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in det_spanish_lit %}
                                <tr>
                                    <td>{{ d.id }}</td>
                                    <td>{{ d.pais }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No catalog items are available/found for Spanish Literature Codes</p>
            {% endif %}
        </div>

    </div>

{% endblock %}

personalLib/library/templates/library/detail.html
<h1>Book Detail. DB_ID: {{ book.id }}</h1>
<br>
<ul>Catalog Id: {{ book.libro_id }}</ul>
<ul>Title: {{ book.titulo }}</ul>
<ul>Author: {{ book.autor }}</ul>
<ul>Num. Pags.: {{ book.pags }}</ul>
<ul>Editorial: {{ book.editorial }}</ul>
<ul>ISBN: {{ book.isbn }}</ul>
<ul>Read?: {{ book.leido }}</ul>
<ul>Comments: {{ book.observaciones }}</ul>

personalLib/library/templates/library/dewey_system.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <!-- <div class="col-md-12 text-center mb-12"> -->
                <h2 class="heading-section">Used Dewey Catalogation System</h2>
            <!-- </div> -->
        </div>
        {% if determinants %}
            <div class="row">
                <div class="table-wrap">
                    <table class="table table-bordered table-dark table-hover table-narrow">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in determinants %}
                                <tr>
                                    <td>{{ d.id }}</td>
                                    <td>{{ d.nombre }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <p>No catalog items are available/found.</p>
        {% endif %}
    </div>
{% endblock %}

personalLib/library/templates/library/home.html
{% extends 'base/generic.html' %}

{% block content %}
    <div class="container-card">
        <div class="panel card-2 card-dark">
            <h1 class="text-center">Personal Library Home</h1>

            <p>Welcome {{ user.get_username }} to my personal library!</p>
            <p>Website developed in Django by me, by Carlitos!!!</p>
            <h2>Some Counters:</h2>
            <ul>
                <li><strong>Books:</strong> {{ total_books }}</li>
                <li><strong>Authors:</strong> {{ total_authors }}</li>
            </ul>
        </div>
    </div>
{% endblock %}